id = "ucode"
name = "UCode"
version = "0.1.1"
schema_version = 1
authors = ["Paul White <phwhite@gmail.com>"]
description = "UCode language support: grammar + highlighting (incl. template strings), brackets, outline & indents."
repository = "https://github.com/phwhite/ucode-zed"

[grammars.ucode]
repository = "https://github.com/phwhite/tree-sitter-ucode"
rev = "d6024ed7928f435b33133d97ff220f5e0bdbbae8"

