name = "UCode"
grammar = "ucode"
path_suffixes = ["uc"]

line_comments = ["// "]
tab_size = 4
hard_tabs = false

# Match: #!/usr/bin/ucode  or  #!/usr/local/bin/ucode
first_line_pattern = "^#!\\s*(?:/usr/(?:local/)?bin/ucode)(?:\\s|$)"
