name = "ucode"
grammar = "ucode"
path_suffixes = ["uc"]

# Comment patterns from ucode (JavaScript-style)
line_comments = ["// ", "# "]
block_comments = [["/*", "*/"]]
tab_size = 4
hard_tabs = false

# Match: #!/usr/bin/ucode or #!/usr/local/bin/ucode
first_line_pattern = "^#!\\s*(?:/usr/(?:local/)?bin/ucode)(?:\\s|$)"

# Auto-closing brackets configuration
brackets = [
    { start = "(", end = ")", close = true, newline = false },
    { start = "[", end = "]", close = true, newline = false },
    { start = "{", end = "}", close = true, newline = true },
    { start = "'", end = "'", close = true, newline = false, not_in = ["string"] },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
    { start = "`", end = "`", close = true, newline = false, not_in = ["string"] }
]

# Override settings for specific syntax scopes
[overrides.string]
# Disable auto-close in strings to prevent interference
auto_close = false

[overrides.comment]
# Disable auto-close in comments
auto_close = false
